# Test that the base container can install necessary software
FROM jfloff/alpine-python:recent-onbuild
RUN git clone -b prereleases/v23 https://github.com/rainbow-mind-machine/rainbow-mind-machine.git rmm
RUN cd /rmm && \
    /usr/bin/env pip install -r requirements.txt
